name: flowing-package-builder

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Prepare build-system
        run: pip install setuptools build
      - name: Install flowing
        run: pip install .
      - name: Test import
        run: python -c "import flowing"
      - name: Package flowing
        run: python -m build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ${{ github.workspace }}/dist
      - name: Upload code
        uses: actions/upload-artifact@v4
        with:
          name: code
          path: ${{ github.workspace }}/flowing